### ISSUE TITLE
CSS for "dismiss" text shouldn't allow text to be broken w/ newlines

### ISSUE THREAD

**Issue by 4815162342** [HuxTechnology/backlog#16]
![image](https://cloud.githubusercontent.com/assets/3502951/26741420/47d352d8-47a7-11e7-97e5-d94aeb98f96d.png)

**Comment by stanleyness** [comment]
should just be X

**Comment by jamesloper** [comment]
should we remove the gesture dismiss and replace with a button?

**Comment by stanleyness** [comment]
yes


*Stanley Vergilis*
CEO
(404) 422-5330
hux.com

**Comment by johnnietirado** [comment]
Done.
