### ISSUE TITLE
[Profile] Margin needed between rows of photos

### ISSUE THREAD

**Issue by 4815162342** [HuxTechnology/backlog#25]
![image](https://cloud.githubusercontent.com/assets/3502951/26742674/a6dfdada-47ac-11e7-8c42-859465fec25f.png)

**Comment by 4815162342** [comment]
Also, consider decreasing the horizontal margin. Make those photos bigger!

**Comment by stanleyness** [comment]
this needs to be per design

**Comment by johnnietirado** [comment]
Resolved in other Issue.
